### ISSUE TITLE
Could not find module `d3-path` imported from `d3-shape/src/arc`

### ISSUE THREAD

**Issue by rlivsey** [ivanvanderbyl/ember-cli-d3-shape-shim#1]
Just came across this addon and your other d3-shim when looking to get d3-shape working in an Ember app.

They aren't in NPM, so understand they might not be completely done yet!

I installed by adding the github references to package.json:

``` json
"ember-cli-d3-shape-shim": "ivanvanderbyl/ember-cli-d3-shape-shim",
"ember-d3-shim": "ivanvanderbyl/ember-d3-shim"
```

Then attempting the example import in my app:

``` javascript
import { line, area, pie } from "d3-shape";
```

gives the error: 

```
Uncaught Error: Could not find module `d3-path` imported from `d3-shape/src/arc`
```

Are there any steps I'm missing to get this up and running?

Thanks.

**Comment by ivanvanderbyl** [comment]
Hey there @rlivsey, thanks for pointing that out. It's actually an unresolved issue with the way I shimmed this library. Basically we build a tree of its source and assume it as out own. The downside to this is that we have to somehow load dependencies in to this tree as well, and I haven't had time to investigate a good way to do this. 

I quick workaround would be to just shim `d3-path` as well using the same strategy and add it as a dependency of this shim.

In the long run I want to figure out how to make broccoli load each dependency as a named tree so doing `import {path} from 'd3-path' does what you would expect. Unfortunately at the moment`d3-path` isn't in the dependency tree of your app so it doesn't get loaded by broccoli.

**Comment by ivanvanderbyl** [comment]
If you install `ivanvanderbyl/ember-cli-d3-path-shim` in your ember app it will resolve this issue. I need to reconsider this whole shimming approach and find a more generalized approach going forward.

**Comment by rlivsey** [comment]
Great stuff, thanks - adding ember-cli-d3-path-shim and pinning it to ivanvanderbyl/ember-cli-d3-path-shim@95661453f5abb7b877817aec859ada5a86f2eb20 does the trick.

**Comment by ivanvanderbyl** [comment]
That's the go. I'm working on a better way to shim this so all d3 v4
packages can be loaded from one package.

**Comment by ivanvanderbyl** [comment]
@rlivsey I've released a new package which wraps all the important D3 v4 packages for Ember. Give it a try https://github.com/ivanvanderbyl/ember-cli-d3-primitive

**Comment by rlivsey** [comment]
Awesome, thanks - I'll take it for a spin this evening.
